version: '3.8'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bdd_incident_responder
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  threat-detection-service:
    image: trustno/detectionapp
    container_name: detection
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKER: kafka:9092  # Kafka broker address
    depends_on:
      - kafka
    command: >
      sh -c "./entrypoint.sh"


  django_app:
    image: trustno/djangoapp
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: >
      sh -c "./entrypoint.sh"

