version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bdd_incident_responder
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  django_app:
    image: trustno/django_app
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: >
      sh -c "./entrypoint.sh"
  
