# Generated by Django 5.1.3 on 2024-11-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField(default='blockIP')),
                ('source', models.TextField(default='ThreatDetectionService')),
            ],
        ),
    ]
